### PR TITLE
Ob queue simplified

### PR DESCRIPTION
**Pull request by gilbox**
- Includes major change to `stateChanged` and how previous state is tracked per component which ensures that SCU returns false after render.

- No longer need to check if OB changed in SCU.

- Simplified `stateChanged`.

- I'm not sure if i should have overwritten the old `Mixin#getPreviousState`

### CODE REVIEW

**Comment by Tvaroh** [comment]
Cool, thank, Gil! I will review and hopefully merge today-tomorrow.

**Comment by Tvaroh** [comment]
Gil, wouldn't `previousState !== currentBinding.get()` incorrectly return true [here](https://github.com/gilbox/moreartyjs/blob/51f553d59d37b30924cc548452dda8422c9d5d85/src/Morearty.js#L29) since `previousState` is in fact a backing value?

**Comment by Tvaroh** [comment]
I see, you've overridden `_previousState`.

**Comment by Tvaroh** [comment]
Gil, I made some commits and restored `getPreviousState` API since we probably don't need to expose these mechanics and better prevent public API changes. Could you review?

**Comment by Tvaroh** [comment]
Looks like we may release this stuff, Gil?

**Comment by gilbox** [comment]
I think maybe wait a few more days just to make sure. I'll try to test it out some more.

**Comment by Tvaroh** [comment]
Okay, sure.

**Pull request closed without merging**
