### PR TITLE
react-native support

### PR DESCRIPTION
**Pull request by gilbox**
Adds react-native support via

```
var Morearty = require('morearty/native');
```

Could be improved by exploring different [timing strategies](https://facebook.github.io/react-native/docs/timers.html#content)

### CODE REVIEW

**Comment by gilbox** [comment]
I had to remove the `react` peerDependency. An alternative is to generate two custom builds with a script in package.json and separately publish `morearty-native`.

**Comment by Tvaroh** [comment]
Cool, Gil, thanks. I will review and merge today-tomorrow.

**Comment by Tvaroh** [comment]
Gil, I built using `npm run build` and can't see DOM module in the generated source.

**Comment by gilbox** [comment]
Sorry I wasn't more clear. I did not implement the npm script command. I was waiting to hear from you if you thought it was a good idea to have two separate npm packages: `morearty` and `morearty-native`. Should I go ahead and implement it?

**Comment by Tvaroh** [comment]
I like having a single package and use `require('morearty/native')` for native. What do you think?

**Comment by gilbox** [comment]
I like it too. I don't know if the missing peerDependency will confuse people ¯\_(ツ)_/¯

**Comment by Tvaroh** [comment]
Gil, we can't merge this PR since the resulting build has no DOM module inside - browsers will miss it.

**Comment by gilbox** [comment]
Can you please explain? Do you mean `Morearty.DOM`? It is still there.

**Comment by Tvaroh** [comment]
I mean when I built with `npm run build` and opened `dist/morearty*.js` I saw no DOM code in the generated file.

**Comment by gilbox** [comment]
Ok, I [fixed it](https://github.com/gilbox/moreartyjs/commit/dc5c288ac5453cbfa19e3b22bd91daa4b8415854)

**Comment by Tvaroh** [comment]
Sorry for the delay. Merged finally!

**Pull request closed without merging**
